<h1 class="cover-heading">PHP Captcha Protector.</h1>
<p class="lead">
    This is a tiny library class, you can use to protect any page or form into your project from brute-force hacking or spam.
    The code is really simple, see examples: <a href="./?page=login">protecting Login Form</a> and <a href="/?page=search">protecting Search Form</a>
</p>
<p class="lead">
    <a target="_blank" href="https://github.com/jakulov/captcha-protector" class="btn btn-lg btn-default">See at GitHub</a>
</p>