<h1 class="cover-heading">PHP Captcha Protector.</h1>
<p class="lead">
    This is a tiny library class, you can use to protect any page or form into your project from brute-force hacking or spam.
    The code is really simple, see examples: <a style="color: aqua" href="./?page=login">protecting Login Form</a> and <a style="color: aqua" href="/?page=search">protecting Search Form</a>
</p>
<p class="lead">
    <a href="./?page=login" class="btn btn-lg btn-primary">Example 1<br><small>Login form</small></a>
    <a href="./?page=search" class="btn btn-lg btn-primary">Example 2<br><small>Search form</small></a>
    <a target="_blank" href="https://github.com/jakulov/captcha-protector" class="btn btn-lg btn-default">Source at GitHub<br><small>jakulov</small></a>
</p>